global:
  scrape_interval: 1s #Scrape interval to every 15 seconds.
  evaluation_interval: 1s #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
